# @section karpenter begin
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: karpenter
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  sources:
    - repoURL: public.ecr.aws
      chart: karpenter/karpenter
      targetRevision: 1.4.0
      helm:
        valueFiles:
          - $values/helm/karpenter/values.yaml
    # @param argocd.git_repo_url
    - repoURL: git@github.com:myorg/my-argocd-repo.git
      # @param argocd.git_target_revision
      targetRevision: main
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
# @section karpenter end