loki:
  auth_enabled: false
  commonConfig:
    path_prefix: /var/loki
    replication_factor: 1
  schemaConfig:
    configs:
      - from: "2024-04-01"
        store: tsdb
        object_store: s3
        schema: v13
        index:
          prefix: loki_index_
          period: 24h
  storage_config:
    aws:
      region: eu-west-1
      bucketnames: 559050227177-brc7aeks-dev-loki-chunk # Your actual S3 bucket name, for example, loki-aws-dev-chunks
      s3forcepathstyle: false
  # ingester:
  #   chunk_encoding: snappy
  pattern_ingester:
    enabled: true
  limits_config:
    allow_structured_metadata: true
    volume_enabled: true
    retention_period: 672h # 28 days retention
  # compactor:
  #    retention_enabled: true 
  #    delete_request_store: s3
  ruler:
    enable_api: true
  #   storage:
  #     type: s3
  #     s3:
  #       region: eu-west-1
  #       bucketnames: 284885114462-ara-eks-dev-loki-ruler # Your actual S3 bucket name, for example, loki-aws-dev-ruler
  #       s3forcepathstyle: false
  #     alertmanager_url: http://prometheus-stack-kube-prom-alertmanager:9093 # The URL of the Alertmanager to send alerts (Prometheus, Mimir, etc.)

  # querier:
  #   max_concurrent: 2

  storage:
    type: s3
    bucketNames:
      chunks: 559050227177-brc7aeks-dev-loki-chunk # Your actual S3 bucket name (loki-aws-dev-chunks)
      ruler: 559050227177-brc7aeks-dev-loki-ruler # Your actual S3 bucket name (loki-aws-dev-ruler)
    s3:
      region: eu-west-1

  podAnnotations:
    iam.amazonaws.com/role-arn: arn:aws:iam::559050227177:role/559050227177-brc7aeks-dev-loki-20251219140756968600000005

serviceAccount:
  create: true
  name: loki-sa
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::559050227177:role/559050227177-brc7aeks-dev-loki-20251219140756968600000005

# Disable minio storage
minio:
  enabled: false

deploymentMode: SingleBinary

singleBinary:
  replicas: 1
  persistence:
    storageClass: gp2
    accessModes:
      - ReadWriteOnce
    size: 10Gi

# Zero out replica counts of other deployment modes
backend:
  replicas: 0
read:
  replicas: 0
write:
  replicas: 0

ingester:
  replicas: 0
querier:
  replicas: 0
queryFrontend:
  replicas: 0
queryScheduler:
  replicas: 0
distributor:
  replicas: 0
compactor:
  replicas: 0
indexGateway:
  replicas: 0
bloomCompactor:
  replicas: 0
bloomGateway:
  replicas: 0