# # 1) Make sure the cattle-system namespace exists
# kubectl create namespace cattle-system

# # 2) Create a bootstrap-secret with your chosen password
# kubectl -n cattle-system create secret generic bootstrap-secret --from-literal=bootstrapPassword='YourAdminPassword123'

replicas: 1
tls: external
ingress:
  enabled: true
  servicePort: 80
  tls:
    source: ""
  ingressClassName: "nginx"
hostname: rancher.openprime.io
fleet:
  enabled: false

extraObjects:
- apiVersion: rbac.authorization.k8s.io/v1
  kind: ClusterRole
  metadata:
    name: cluster-admin
  rules:
    - apiGroups: ["*"]
      resources: ["*"]
      verbs: ["*"]
    - nonResourceURLs: ["*"]
      verbs: ["*"]
