# Alertmanager configuration
alertmanager:
  enabled: true
  config:
    global:
      resolve_timeout: 5m

    route:
      receiver: "slack"
      group_by: [ "alertname", "job" ]
      group_wait: 30s
      group_interval: 5m
      repeat_interval: 4h
      routes:
      - receiver: "slack-critical"
        matchers:
        - severity = "critical"
        continue: true

      - receiver: "email-critical"
        matchers:
        - severity = "critical"
        continue: true

      - receiver: "slack"
        matchers:
        - severity = "warning"
        continue: true

      - receiver: "email-warning"
        matchers:
        - severity = "warning"
        continue: true

    receivers:
    - name: slack
      slack_configs:
      - channel: "#channel-name" # Add your Slack channel name
        api_url: "ADD_YOUR_SLACK_HOOK" # Add your Slack hook 
        color: '{{ if eq .Status "firing" }}{{ if eq .CommonLabels.severity "warning" }}warning{{ else if eq .CommonLabels.severity "critical" }}danger{{ else }}#439FE0{{ end }}{{ else }}good{{ end }}'
        title: '[{{ .Status | toUpper }}] {{ .CommonLabels.alertname }}'
        text: |
          {{- if eq .CommonLabels.severity "critical" -}}
          *Severity:* `Critical`
          {{- else if eq .CommonLabels.severity "warning" -}}
          *Severity:* `Warning`
          {{- else if eq .CommonLabels.severity "info" -}}
          *Severity:* `Info`
          {{- else -}}
          *Severity:* {{ .CommonLabels.severity }}
          {{- end }}
          {{ range .Alerts }}
            {{- if .Annotations.description }}
            {{ .Annotations.description }}
            {{- end }}
            {{- if .Annotations.message }}
            {{ .Annotations.message }}
            {{- end }}
          {{ end }}
        send_resolved: true

    - name: slack-critical
      slack_configs:
      - channel: "#channel-name" # Add your Slack channel name
        api_url: "ADD_YOUR_SLACK_HOOK" # Add your Slack hook 
        color: '{{ if eq .Status "firing" }}{{ if eq .CommonLabels.severity "warning" }}warning{{ else if eq .CommonLabels.severity "critical" }}danger{{ else }}#439FE0{{ end }}{{ else }}good{{ end }}'
        title: '[{{ .Status | toUpper }}] {{ .CommonLabels.alertname }}'
        text: |
          {{- if eq .CommonLabels.severity "critical" -}}
          *Severity:* `Critical`
          {{- else if eq .CommonLabels.severity "warning" -}}
          *Severity:* `Warning`
          {{- else if eq .CommonLabels.severity "info" -}}
          *Severity:* `Info`
          {{- else -}}
          *Severity:* {{ .CommonLabels.severity }}
          {{- end }}
          {{ range .Alerts }}
            {{- if .Annotations.description }}
            {{ .Annotations.description }}
            {{- end }}
            {{- if .Annotations.message }}
            {{ .Annotations.message }}
            {{- end }}
          {{ end }}
        send_resolved: true

    - name: email-critical
      email_configs:
      - to: "RECEIVERS_EMAIL_ADDRESS" # Receiver email username
        from: "YOUR_EMAIL_ADDRESS" # Your email username
        smarthost: "smtp.gmail.com:587" # Correct email SMTP server and port
        auth_username: "YOUR_EMAIL_ADDRESS" # Your email username
        auth_password: "EMAIL_APP_PASSWORD" # Your email App Password
        require_tls: true
        send_resolved: true
        html: |
          <strong>Severity:</strong> {{ .CommonLabels.severity }}<br>
          <strong>Alert Name:</strong> {{ .CommonLabels.alertname }}<br>
          {{ range .Alerts }}
            {{- if .Annotations.description }}
            <strong>Description:</strong> {{ .Annotations.description }}<br>
            {{- end }}
          {{ end }}

    - name: email-warning
      email_configs:
      - to: "RECEIVERS_EMAIL_ADDRESS" # Receiver email username
        from: "YOUR_EMAIL_ADDRESS" # Your email username
        smarthost: "smtp.gmail.com:587" # Correct email SMTP server and port
        auth_username: "YOUR_EMAIL_ADDRESS" # Your email username
        auth_password: "EMAIL_APP_PASSWORD" # Your email App Password
        require_tls: true
        send_resolved: true
        html: |
          <strong>Severity:</strong> {{ .CommonLabels.severity }}<br>
          <strong>Alert Name:</strong> {{ .CommonLabels.alertname }}<br>
          {{ range .Alerts }}
            {{- if .Annotations.description }}
            <strong>Description:</strong> {{ .Annotations.description }}<br>
            {{- end }}
          {{ end }}

  templateFiles:
    slack.tmpl: |-
      {{/* Alertmanager Silence link */}}
      {{ define "__alert_silence_link" -}}
          {{ .ExternalURL }}/#/silences/new?filter=%7B
          {{- range .CommonLabels.SortedPairs -}}
              {{- if ne .Name "alertname" -}}
                  {{- .Name }}%3D"{{- .Value -}}"%2C%20
              {{- end -}}
          {{- end -}}
          alertname%3D"{{- .CommonLabels.alertname -}}"%7D
      {{- end }}

      {{/* Severity of the alert */}}
      {{ define "__alert_severity" -}}
          {{- if eq .CommonLabels.severity "critical" -}}
          *Severity:* `Critical`
          {{- else if eq .CommonLabels.severity "warning" -}}
          *Severity:* `Warning`
          {{- else if eq .CommonLabels.severity "info" -}}
          *Severity:* `Info`
          {{- else -}}
          *Severity:* :question: {{ .CommonLabels.severity }}
          {{- end }}
      {{- end }}

      {{/* Title of the Slack alert */}}
      {{ define "slack.title" -}}
        [{{ .Status | toUpper -}}
        {{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{- end -}}
        ] {{ .CommonLabels.alertname }}
      {{- end }}... 

      {{ define "slack.color" -}}
          {{ if eq .Status "firing" -}}
              {{ if eq .CommonLabels.severity "warning" -}}
                  warning
              {{- else if eq .CommonLabels.severity "critical" -}}
                  danger
              {{- else -}}
                  #439FE0
              {{- end -}}
          {{ else -}}
          good
          {{- end }}
      {{- end }}

      {{/* The text to display in the alert */}}
      {{ define "slack.text" -}}

          {{ template "__alert_severity" . }}
          {{- if (index .Alerts 0).Annotations.summary }}
          {{- "\n" -}}
          *Summary:* {{ (index .Alerts 0).Annotations.summary }}
          {{- end }}

          {{ range .Alerts }}

              {{- if .Annotations.description }}
              {{- "\n" -}}
              {{ .Annotations.description }}
              {{- "\n" -}}
              {{- end }}
              {{- if .Annotations.message }}
              {{- "\n" -}}
              {{ .Annotations.message }}
              {{- "\n" -}}
              {{- end }}

          {{- end }}

      {{- end }}
