controller:
  admissionWebhooks:
    service:
      annotations:
        argocd.argoproj.io/sync-wave: "-1"

  service:
    annotations:
      # TODO: TLS
      # service.beta.kubernetes.io/aws-load-balancer-ssl-cert: "arn:aws:acm:region:acc_id:certificate/xxxxxxxxxxx"
      # service.beta.kubernetes.io/aws-load-balancer-ssl-ports: "https"
      service.beta.kubernetes.io/aws-load-balancer-backend-protocol: "http"
      service.beta.kubernetes.io/aws-load-balancer-connection-idle-timeout: "3600"
      service.beta.kubernetes.io/aws-load-balancer-type: "external"
      service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
      service.beta.kubernetes.io/aws-load-balancer-proxy-protocol: "*"
      service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
      argocd.argoproj.io/sync-wave: "-1"
    targetPorts:
      http: "http"
      https: "http" # This maps HTTPS port on LB to HTTP port on the pod
  resources:
    requests:
      cpu: 100m
      memory: 128Mi

  metrics:
    enabled: true

  autoscaling:
    enabled: true
    minReplicas: 1
    maxReplicas: 5
    targetCPUUtilizationPercentage: 80
